-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 11:34:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Blog` ;

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`Authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Authors` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(70) NOT NULL,
  `firstName` VARCHAR(70) NULL,
  `pseudo` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pseudo_UNIQUE` ON `Blog`.`Authors` (`pseudo` ASC);


-- -----------------------------------------------------
-- Table `Blog`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Posts` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NOT NULL,
  `content` VARCHAR(150) NOT NULL,
  `publicationStartDate` DATETIME NOT NULL,
  `publicationEndDate` DATETIME NOT NULL,
  `importance` INT NOT NULL DEFAULT 0,
  `Authors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Posts_Authors`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `Blog`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Posts_Authors_idx` ON `Blog`.`Posts` (`Authors_id` ASC);


-- -----------------------------------------------------
-- Table `Blog`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Categories` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Comments` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT NOW(),
  `Authors_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Comments_Authors1`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `Blog`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `Blog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comments_Authors1_idx` ON `Blog`.`Comments` (`Authors_id` ASC);

CREATE INDEX `fk_Comments_Posts1_idx` ON `Blog`.`Comments` (`Posts_id` ASC);


-- -----------------------------------------------------
-- Table `Blog`.`Categories_has_Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Categories_has_Posts` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Categories_has_Posts` (
  `Categories_id` INT NOT NULL,
  `Posts_id` INT NOT NULL,
  PRIMARY KEY (`Categories_id`, `Posts_id`),
  CONSTRAINT `fk_Categories_has_Posts_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `Blog`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Posts_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `Blog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Categories_has_Posts_Posts1_idx` ON `Blog`.`Categories_has_Posts` (`Posts_id` ASC);

CREATE INDEX `fk_Categories_has_Posts_Categories1_idx` ON `Blog`.`Categories_has_Posts` (`Categories_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
